---
# 基础配置
server:
  # 设置运行端口
  port: 9910
  servlet:
    # 设置项目路径
    context-path: /authorization
spring:
  application:
    # 项目名
    name: authorization
logging:
  level:
    # 对全局debug以上等级的日志进行打印
    root: debug
...

---
# eureka相关配置
eureka:
  client:
    service-url:
      # 注册中心地址需登录账号密码 TODO 需要动态化
      defaultZone: http://user:user@localhost:8761/eureka
    # 向注册中心注册
    register-with-eureka: true
    # 拉取注册列表
    fetch-registry: true
...