server:
  port: 9920
  servlet:
    context-path: /resource
security:
  oauth2:
    client:
      client-id: client_id
      client-secret: 666
    resource:
      token-info-uri: http://localhost:9910/authorization/oauth/check_token
logging:
  level:
    root: debug
spring:
  application:
    name: resuorce